// Code generated by ggen; DO NOT EDIT.

package auth

import (
	"strings"
	"unsafe"

	"github.com/sirkostya009/ggen"
)

func (recv header) DecodeFrom(data []byte) (result header, i int, err error) {
	result = recv
	seenAlg := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenAlg {
			result.Alg = ""
		}
		if !seenAlg {
			return result, i, &ggen.RequiredError{Pos: i, Path: []string{"alg"}}
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "alg":
			if seenAlg {
				i, err = ggen.SkipValue(data, i)
				if err != nil {
					return result, i, ggen.NewParseErr("alg", i, err)
				}
			} else {
				seenAlg = true
				if i >= len(data) || data[i] != '"' {
					return result, i, ggen.NewParseErr("alg", i, ggen.ErrExpectString)
				}
				ke := i + 1
				kew := ke + 32
				if kew > len(data) {
					kew = len(data)
				}
				for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
				if ke < len(data) && data[ke] == '"' {
					result.Alg = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					result.Alg, i, err = ggen.String(data, i, true)
					if err != nil {
						return result, i, ggen.NewParseErr("alg", i, err)
					}
				}
			}
		default:
			i, err = ggen.SkipValue(data, i)
			if err != nil {
				return result, i, ggen.NewParseErr(key, i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenAlg {
				result.Alg = ""
			}
			if !seenAlg {
				return result, i, &ggen.RequiredError{Pos: i, Path: []string{"alg"}}
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv header) DecodeFromStream(s *ggen.Stream) (result header, err error) {
	result = recv
	seenAlg := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenAlg {
			result.Alg = ""
		}
		if !seenAlg {
			return result, &ggen.RequiredError{Pos: s.Offset(), Path: []string{"alg"}}
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "alg":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("alg", s.Offset(), err)
			}
			if seenAlg {
				err = s.SkipValue()
				if err != nil {
					return result, ggen.NewParseErr("alg", s.Offset(), err)
				}
			} else {
				seenAlg = true
				result.Alg, err = s.String(true)
				if err != nil {
					return result, ggen.NewParseErr("alg", s.Offset(), err)
				}

			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			err = s.SkipValue()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenAlg {
				result.Alg = ""
			}
			if !seenAlg {
				return result, &ggen.RequiredError{Pos: s.Offset(), Path: []string{"alg"}}
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s header) JSONSize() int {
	size := 10
	size += len(s.Alg) * 2
	return size
}

func (s header) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"alg\":\""...)
	dst = ggen.AppendStringNoHTML(dst, s.Alg)
	return append(dst, '}'), nil
}

func (recv claims) DecodeFrom(data []byte) (result claims, i int, err error) {
	result = recv
	seenExp := false
	seenSub := false
	seenUsername := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenExp {
			result.Exp = nil
		}
		if !seenSub {
			result.Sub = nil
		}
		if !seenUsername {
			result.Username = nil
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "exp":
			if seenExp {
				i, err = ggen.SkipValue(data, i)
				if err != nil {
					return result, i, ggen.NewParseErr("exp", i, err)
				}
			} else {
				seenExp = true
				result.Exp, i, err = ggen.Any(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("exp", i, err)
				}
			}
		case "sub":
			if seenSub {
				i, err = ggen.SkipValue(data, i)
				if err != nil {
					return result, i, ggen.NewParseErr("sub", i, err)
				}
			} else {
				seenSub = true
				result.Sub, i, err = ggen.Any(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("sub", i, err)
				}
			}
		case "username":
			if seenUsername {
				i, err = ggen.SkipValue(data, i)
				if err != nil {
					return result, i, ggen.NewParseErr("username", i, err)
				}
			} else {
				seenUsername = true
				result.Username, i, err = ggen.Any(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("username", i, err)
				}
			}
		default:
			i, err = ggen.SkipValue(data, i)
			if err != nil {
				return result, i, ggen.NewParseErr(key, i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenExp {
				result.Exp = nil
			}
			if !seenSub {
				result.Sub = nil
			}
			if !seenUsername {
				result.Username = nil
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv claims) DecodeFromStream(s *ggen.Stream) (result claims, err error) {
	result = recv
	seenExp := false
	seenSub := false
	seenUsername := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenExp {
			result.Exp = nil
		}
		if !seenSub {
			result.Sub = nil
		}
		if !seenUsername {
			result.Username = nil
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "exp":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("exp", s.Offset(), err)
			}
			if seenExp {
				err = s.SkipValue()
				if err != nil {
					return result, ggen.NewParseErr("exp", s.Offset(), err)
				}
			} else {
				seenExp = true
				result.Exp, err = s.Any(true)
				if err != nil {
					return result, ggen.NewParseErr("exp", s.Offset(), err)
				}

			}
		case "sub":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("sub", s.Offset(), err)
			}
			if seenSub {
				err = s.SkipValue()
				if err != nil {
					return result, ggen.NewParseErr("sub", s.Offset(), err)
				}
			} else {
				seenSub = true
				result.Sub, err = s.Any(true)
				if err != nil {
					return result, ggen.NewParseErr("sub", s.Offset(), err)
				}

			}
		case "username":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("username", s.Offset(), err)
			}
			if seenUsername {
				err = s.SkipValue()
				if err != nil {
					return result, ggen.NewParseErr("username", s.Offset(), err)
				}
			} else {
				seenUsername = true
				result.Username, err = s.Any(true)
				if err != nil {
					return result, ggen.NewParseErr("username", s.Offset(), err)
				}

			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			err = s.SkipValue()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenExp {
				result.Exp = nil
			}
			if !seenSub {
				result.Sub = nil
			}
			if !seenUsername {
				result.Username = nil
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s claims) JSONSize() int {
	size := 27
	size += ggen.AnySize(s.Exp)
	size += ggen.AnySize(s.Sub)
	size += ggen.AnySize(s.Username)
	return size
}

func (s claims) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"exp\":"...)
	if dst, err = ggen.AppendAny(dst, s.Exp); err != nil {
		return dst, err
	}
	dst = append(dst, ",\"sub\":"...)
	if dst, err = ggen.AppendAny(dst, s.Sub); err != nil {
		return dst, err
	}
	dst = append(dst, ",\"username\":"...)
	if dst, err = ggen.AppendAny(dst, s.Username); err != nil {
		return dst, err
	}
	return append(dst, '}'), nil
}
