// Code generated by rr. DO NOT EDIT.

package httpapi

import (
	"feed/domain"
	"github.com/sirkostya009/ggen"
	"net/http"
	"strings"
	"sync"
)

var __jsonCT = []string{"application/json"}

var readBufPool = sync.Pool{New: func() any { b := make([]byte, 0, 4096); return &b }}

func readJSON[T ggen.StreamDecoder[T]](r *http.Request) (T, error) {
	bp := readBufPool.Get().(*[]byte)
	defer readBufPool.Put(bp)
	var s ggen.Stream
	s.Reset(r.Body, *bp)
	var zero T
	v, err := zero.DecodeFromStream(&s)
	*bp = s.Bytes()
	return v, err
}

func (s *Api) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	var err error
	var feed domain.Feed
	var createPost domain.CreatePost
	var postEnvelope domain.PostEnvelope
	var like domain.Like
	path := r.URL.Path
	if len(path) < 1 || path[:1] != "/" {
		notFound(w)
		return
	}
	path = path[1:]
	switch path {
	case "feed":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			methodNotAllowed(w)
			return
		}
		r.Pattern = "GET /feed"
		feed, err = s.FeedApi.Feed(r.Context())
		if err != nil {
			handleError(r.Context(), w, err)
			return
		}
		w.Header()["Content-Type"] = __jsonCT
		if err := ggen.WriteTo(w, feed); err != nil {
			handleError(r.Context(), w, err)
			return
		}
		return
	case "health":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			methodNotAllowed(w)
			return
		}
		r.Pattern = "GET /health"
		w.Header()["Content-Type"] = __jsonCT
		if err := ggen.WriteTo(w, s.HealthApi.Health(r.Context(), w)); err != nil {
			handleError(r.Context(), w, err)
			return
		}
		return
	case "posts":
		if r.Method != "POST" {
			w.Header().Set("Allow", "POST")
			methodNotAllowed(w)
			return
		}
		r.Pattern = "POST /posts"
		if !requireUser(r.Context(), w) {
			return
		}
		createPost, err = readJSON[domain.CreatePost](r)
		if err != nil {
			badRequest(w, err)
			return
		}
		postEnvelope, err = s.PostsApi.Create(r.Context(), w, createPost)
		if err != nil {
			handleError(r.Context(), w, err)
			return
		}
		w.Header()["Content-Type"] = __jsonCT
		if err := ggen.WriteTo(w, postEnvelope); err != nil {
			handleError(r.Context(), w, err)
			return
		}
		return
	}
	if len(path) >= 6 && path[:6] == "posts/" {
		path = path[6:]
		if i := strings.IndexByte(path, '/'); i < 0 {
			if path != "" {
				if r.Method != "GET" {
					w.Header().Set("Allow", "GET")
					methodNotAllowed(w)
					return
				}
				r.Pattern = "GET /posts/{id}"
				postEnvelope, err = s.FeedApi.Get(r.Context(), path)
				if err != nil {
					handleError(r.Context(), w, err)
					return
				}
				w.Header()["Content-Type"] = __jsonCT
				if err := ggen.WriteTo(w, postEnvelope); err != nil {
					handleError(r.Context(), w, err)
					return
				}
				return
			}
		} else if i > 0 {
			s1 := path[:i]
			path = path[i+1:]
			if path == "like" {
				if r.Method != "POST" {
					w.Header().Set("Allow", "POST")
					methodNotAllowed(w)
					return
				}
				r.Pattern = "POST /posts/{id}/like"
				if !requireUser(r.Context(), w) {
					return
				}
				like, err = s.PostsApi.Like(r.Context(), w, s1)
				if err != nil {
					handleError(r.Context(), w, err)
					return
				}
				w.Header()["Content-Type"] = __jsonCT
				if err := ggen.WriteTo(w, like); err != nil {
					handleError(r.Context(), w, err)
					return
				}
				return
			}
		}
	}
	notFound(w)
}
