server.address=${HOST:127.0.0.1}
server.port=${PORT:3000}
server.tomcat.keep-alive-timeout=70s
spring.web.resources.add-mappings=false
spring.jackson.deserialization.fail-on-trailing-tokens=true
spring.main.banner-mode=off
