// Code generated by ggen; DO NOT EDIT.

package domain

import (
	"math"
	"math/bits"
	"simd/archsimd"
	"strconv"
	"strings"
	"unicode/utf8"
	"unsafe"

	"github.com/sirkostya009/ggen"
)

// Tries to fit >2 elements in 80 bytes, then 512 bytes - never goes above that.
const ggenCap_Feed_Posts_Post = (min((80/max(int(unsafe.Sizeof(*new(Post))), 1)), 2)/2)*(80/max(int(unsafe.Sizeof(*new(Post))), 1)) + (1-(min((80/max(int(unsafe.Sizeof(*new(Post))), 1)), 2)/2))*max(((8*int(unsafe.Sizeof(uintptr(0)))*int(unsafe.Sizeof(uintptr(0))))/max(int(unsafe.Sizeof(*new(Post))), 1)), 1)

func (recv Health) DecodeFrom(data []byte) (result Health, i int, err error) {
	result = recv
	seenStatus := false
	seenDB := false
	seenUptimeS := false
	seenError := false
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenStatus {
			result.Status = ""
		}
		if !seenDB {
			result.DB = ""
		}
		if !seenUptimeS {
			result.UptimeS = nil
		}
		if !seenError {
			result.Error = ""
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		if ke+32 <= len(data) {
			keV := archsimd.LoadUint8x32(data[ke:])
			keD := keV.Sub(archsimd.BroadcastUint8x32(0x20))
			keM := keV.Equal(archsimd.BroadcastUint8x32('"')).Or(keV.Equal(archsimd.BroadcastUint8x32('\\'))).Or(keD.Max(archsimd.BroadcastUint8x32(0x60)).Equal(keD)).ToBits()
			if keM != 0 {
				ke += bits.TrailingZeros32(keM)
			}
		} else {
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.StringAVX2(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		switch key {
		case "status":
			if seenStatus {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"status"}}
			}
			seenStatus = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("status", i, ggen.ErrExpectString)
			}
			ke := i + 1
			if ke+32 <= len(data) {
				keV := archsimd.LoadUint8x32(data[ke:])
				keD := keV.Sub(archsimd.BroadcastUint8x32(0x20))
				keM := keV.Equal(archsimd.BroadcastUint8x32('"')).Or(keV.Equal(archsimd.BroadcastUint8x32('\\'))).Or(keD.Max(archsimd.BroadcastUint8x32(0x60)).Equal(keD)).ToBits()
				if keM != 0 {
					ke += bits.TrailingZeros32(keM)
				}
			} else {
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
			}
			if ke < len(data) && data[ke] == '"' {
				result.Status = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Status, i, err = ggen.StringAVX2(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("status", i, err)
				}
			}
		case "db":
			if seenDB {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"db"}}
			}
			seenDB = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("db", i, ggen.ErrExpectString)
			}
			ke := i + 1
			if ke+32 <= len(data) {
				keV := archsimd.LoadUint8x32(data[ke:])
				keD := keV.Sub(archsimd.BroadcastUint8x32(0x20))
				keM := keV.Equal(archsimd.BroadcastUint8x32('"')).Or(keV.Equal(archsimd.BroadcastUint8x32('\\'))).Or(keD.Max(archsimd.BroadcastUint8x32(0x60)).Equal(keD)).ToBits()
				if keM != 0 {
					ke += bits.TrailingZeros32(keM)
				}
			} else {
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
			}
			if ke < len(data) && data[ke] == '"' {
				result.DB = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.DB, i, err = ggen.StringAVX2(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("db", i, err)
				}
			}
		case "uptime_s":
			if seenUptimeS {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"uptime_s"}}
			}
			seenUptimeS = true
			if i < len(data) && data[i] == 'n' {
				if i+4 > len(data) || data[i+1] != 'u' || data[i+2] != 'l' || data[i+3] != 'l' {
					return result, i, ggen.NewParseErr("uptime_s", i, ggen.ErrBadLiteral)
				}
				i += 4
				result.UptimeS = nil
				break
			}
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("uptime_s", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("uptime_s", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("uptime_s", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("uptime_s", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			if result.UptimeS == nil {
				result.UptimeS = new(n)
			} else {
				(*result.UptimeS) = n
			}
		case "error":
			if seenError {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"error"}}
			}
			seenError = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("error", i, ggen.ErrExpectString)
			}
			ke := i + 1
			if ke+32 <= len(data) {
				keV := archsimd.LoadUint8x32(data[ke:])
				keD := keV.Sub(archsimd.BroadcastUint8x32(0x20))
				keM := keV.Equal(archsimd.BroadcastUint8x32('"')).Or(keV.Equal(archsimd.BroadcastUint8x32('\\'))).Or(keD.Max(archsimd.BroadcastUint8x32(0x60)).Equal(keD)).ToBits()
				if keM != 0 {
					ke += bits.TrailingZeros32(keM)
				}
			} else {
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
			}
			if ke < len(data) && data[ke] == '"' {
				result.Error = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Error, i, err = ggen.StringAVX2(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("error", i, err)
				}
			}
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
				if i < len(data) && data[i] <= ' ' {
					i = ggen.SkipSpaceAVX2(data, i)
				}
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenStatus {
				result.Status = ""
			}
			if !seenDB {
				result.DB = ""
			}
			if !seenUptimeS {
				result.UptimeS = nil
			}
			if !seenError {
				result.Error = ""
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv Health) DecodeFromStream(s *ggen.Stream) (result Health, err error) {
	result = recv
	seenStatus := false
	seenDB := false
	seenUptimeS := false
	seenError := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpaceAVX2()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenStatus {
			result.Status = ""
		}
		if !seenDB {
			result.DB = ""
		}
		if !seenUptimeS {
			result.UptimeS = nil
		}
		if !seenError {
			result.Error = ""
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyViewAVX2(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "status":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("status", s.Offset(), err)
			}
			if seenStatus {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"status"}}
			}
			seenStatus = true
			result.Status, err = s.StringAVX2(true)
			if err != nil {
				return result, ggen.NewParseErr("status", s.Offset(), err)
			}
		case "db":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("db", s.Offset(), err)
			}
			if seenDB {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"db"}}
			}
			seenDB = true
			result.DB, err = s.StringAVX2(true)
			if err != nil {
				return result, ggen.NewParseErr("db", s.Offset(), err)
			}
		case "uptime_s":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("uptime_s", s.Offset(), err)
			}
			if seenUptimeS {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"uptime_s"}}
			}
			seenUptimeS = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, ggen.NewParseErr("uptime_s", s.Offset(), ggen.NotEOF(err, ggen.ErrBadNumber))
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, ggen.NewParseErr("uptime_s", s.Offset(), ggen.NotEOF(err, ggen.ErrBadLiteral))
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, ggen.NewParseErr("uptime_s", s.Offset(), ggen.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.UptimeS = nil
				break
			}
			var v int64
			v, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("uptime_s", s.Offset(), err)
			}
			if result.UptimeS == nil {
				result.UptimeS = new(v)
			} else {
				(*result.UptimeS) = v
			}
		case "error":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("error", s.Offset(), err)
			}
			if seenError {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"error"}}
			}
			seenError = true
			result.Error, err = s.StringAVX2(true)
			if err != nil {
				return result, ggen.NewParseErr("error", s.Offset(), err)
			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{ownKey}}
		}

		err = s.SkipSpaceAVX2()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpaceAVX2()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenStatus {
				result.Status = ""
			}
			if !seenDB {
				result.DB = ""
			}
			if !seenUptimeS {
				result.UptimeS = nil
			}
			if !seenError {
				result.Error = ""
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s Health) JSONSize() int {
	size := 21
	size += len(s.Status) * 2
	size += len(s.DB) * 2
	if s.UptimeS != nil {
		size += 32
	}
	if s.Error != "" {
		size += 11
		size += len(s.Error) * 2
	}
	return size
}

func (s Health) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	start := len(dst)
	if len(dst) > start {
		dst = append(dst, ',')
	}
	dst = append(dst, "\"status\":\""...)
	dst = ggen.AppendStringNoHTMLAVX2(dst, s.Status)
	if len(dst) > start {
		dst = append(dst, ',')
	}
	dst = append(dst, "\"db\":\""...)
	dst = ggen.AppendStringNoHTMLAVX2(dst, s.DB)
	if s.UptimeS != nil {
		if len(dst) > start {
			dst = append(dst, ',')
		}
		dst = append(dst, "\"uptime_s\":"...)
		dst = strconv.AppendInt(dst, (*s.UptimeS), 10)
	}
	if s.Error != "" {
		if len(dst) > start {
			dst = append(dst, ',')
		}
		dst = append(dst, "\"error\":\""...)
		dst = ggen.AppendStringNoHTMLAVX2(dst, s.Error)
	}
	return append(dst, '}'), nil
}

func (recv ErrorBody) DecodeFrom(data []byte) (result ErrorBody, i int, err error) {
	result = recv
	seenError := false
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenError {
			result.Error = ""
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		kew := ke + 6
		if kew > len(data) {
			kew = len(data)
		}
		for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.StringAVX2(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		switch key {
		case "error":
			if seenError {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"error"}}
			}
			seenError = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("error", i, ggen.ErrExpectString)
			}
			ke := i + 1
			if ke+32 <= len(data) {
				keV := archsimd.LoadUint8x32(data[ke:])
				keD := keV.Sub(archsimd.BroadcastUint8x32(0x20))
				keM := keV.Equal(archsimd.BroadcastUint8x32('"')).Or(keV.Equal(archsimd.BroadcastUint8x32('\\'))).Or(keD.Max(archsimd.BroadcastUint8x32(0x60)).Equal(keD)).ToBits()
				if keM != 0 {
					ke += bits.TrailingZeros32(keM)
				}
			} else {
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
			}
			if ke < len(data) && data[ke] == '"' {
				result.Error = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Error, i, err = ggen.StringAVX2(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("error", i, err)
				}
			}
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
				if i < len(data) && data[i] <= ' ' {
					i = ggen.SkipSpaceAVX2(data, i)
				}
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenError {
				result.Error = ""
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv ErrorBody) DecodeFromStream(s *ggen.Stream) (result ErrorBody, err error) {
	result = recv
	seenError := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpaceAVX2()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenError {
			result.Error = ""
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "error":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("error", s.Offset(), err)
			}
			if seenError {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"error"}}
			}
			seenError = true
			result.Error, err = s.StringAVX2(true)
			if err != nil {
				return result, ggen.NewParseErr("error", s.Offset(), err)
			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{ownKey}}
		}

		err = s.SkipSpaceAVX2()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpaceAVX2()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenError {
				result.Error = ""
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s ErrorBody) JSONSize() int {
	size := 12
	size += len(s.Error) * 2
	return size
}

func (s ErrorBody) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"error\":\""...)
	dst = ggen.AppendStringNoHTMLAVX2(dst, s.Error)
	return append(dst, '}'), nil
}

func (recv Post) DecodeFrom(data []byte) (result Post, i int, err error) {
	result = recv
	seenID := false
	seenBody := false
	seenCreatedAt := false
	seenAuthor := false
	seenLikeCount := false
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenID {
			result.ID = 0
		}
		if !seenBody {
			result.Body = ""
		}
		if !seenCreatedAt {
			result.CreatedAt = ""
		}
		if !seenAuthor {
			result.Author = ""
		}
		if !seenLikeCount {
			result.LikeCount = 0
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		if ke+32 <= len(data) {
			keV := archsimd.LoadUint8x32(data[ke:])
			keD := keV.Sub(archsimd.BroadcastUint8x32(0x20))
			keM := keV.Equal(archsimd.BroadcastUint8x32('"')).Or(keV.Equal(archsimd.BroadcastUint8x32('\\'))).Or(keD.Max(archsimd.BroadcastUint8x32(0x60)).Equal(keD)).ToBits()
			if keM != 0 {
				ke += bits.TrailingZeros32(keM)
			}
		} else {
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.StringAVX2(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		switch key {
		case "id":
			if seenID {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"id"}}
			}
			seenID = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("id", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("id", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("id", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("id", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			result.ID = n
		case "body":
			if seenBody {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"body"}}
			}
			seenBody = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("body", i, ggen.ErrExpectString)
			}
			ke := i + 1
			if ke+32 <= len(data) {
				keV := archsimd.LoadUint8x32(data[ke:])
				keD := keV.Sub(archsimd.BroadcastUint8x32(0x20))
				keM := keV.Equal(archsimd.BroadcastUint8x32('"')).Or(keV.Equal(archsimd.BroadcastUint8x32('\\'))).Or(keD.Max(archsimd.BroadcastUint8x32(0x60)).Equal(keD)).ToBits()
				if keM != 0 {
					ke += bits.TrailingZeros32(keM)
				}
			} else {
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
			}
			if ke < len(data) && data[ke] == '"' {
				result.Body = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Body, i, err = ggen.StringAVX2(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("body", i, err)
				}
			}
		case "created_at":
			if seenCreatedAt {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"created_at"}}
			}
			seenCreatedAt = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("created_at", i, ggen.ErrExpectString)
			}
			ke := i + 1
			if ke+32 <= len(data) {
				keV := archsimd.LoadUint8x32(data[ke:])
				keD := keV.Sub(archsimd.BroadcastUint8x32(0x20))
				keM := keV.Equal(archsimd.BroadcastUint8x32('"')).Or(keV.Equal(archsimd.BroadcastUint8x32('\\'))).Or(keD.Max(archsimd.BroadcastUint8x32(0x60)).Equal(keD)).ToBits()
				if keM != 0 {
					ke += bits.TrailingZeros32(keM)
				}
			} else {
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
			}
			if ke < len(data) && data[ke] == '"' {
				result.CreatedAt = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.CreatedAt, i, err = ggen.StringAVX2(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("created_at", i, err)
				}
			}
		case "author":
			if seenAuthor {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"author"}}
			}
			seenAuthor = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("author", i, ggen.ErrExpectString)
			}
			ke := i + 1
			if ke+32 <= len(data) {
				keV := archsimd.LoadUint8x32(data[ke:])
				keD := keV.Sub(archsimd.BroadcastUint8x32(0x20))
				keM := keV.Equal(archsimd.BroadcastUint8x32('"')).Or(keV.Equal(archsimd.BroadcastUint8x32('\\'))).Or(keD.Max(archsimd.BroadcastUint8x32(0x60)).Equal(keD)).ToBits()
				if keM != 0 {
					ke += bits.TrailingZeros32(keM)
				}
			} else {
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
			}
			if ke < len(data) && data[ke] == '"' {
				result.Author = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Author, i, err = ggen.StringAVX2(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("author", i, err)
				}
			}
		case "like_count":
			if seenLikeCount {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"like_count"}}
			}
			seenLikeCount = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("like_count", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("like_count", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("like_count", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("like_count", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			result.LikeCount = n
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
				if i < len(data) && data[i] <= ' ' {
					i = ggen.SkipSpaceAVX2(data, i)
				}
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenID {
				result.ID = 0
			}
			if !seenBody {
				result.Body = ""
			}
			if !seenCreatedAt {
				result.CreatedAt = ""
			}
			if !seenAuthor {
				result.Author = ""
			}
			if !seenLikeCount {
				result.LikeCount = 0
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv Post) DecodeFromStream(s *ggen.Stream) (result Post, err error) {
	result = recv
	seenID := false
	seenBody := false
	seenCreatedAt := false
	seenAuthor := false
	seenLikeCount := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpaceAVX2()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenID {
			result.ID = 0
		}
		if !seenBody {
			result.Body = ""
		}
		if !seenCreatedAt {
			result.CreatedAt = ""
		}
		if !seenAuthor {
			result.Author = ""
		}
		if !seenLikeCount {
			result.LikeCount = 0
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyViewAVX2(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "id":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("id", s.Offset(), err)
			}
			if seenID {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"id"}}
			}
			seenID = true
			result.ID, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("id", s.Offset(), err)
			}
		case "body":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("body", s.Offset(), err)
			}
			if seenBody {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"body"}}
			}
			seenBody = true
			result.Body, err = s.StringAVX2(true)
			if err != nil {
				return result, ggen.NewParseErr("body", s.Offset(), err)
			}
		case "created_at":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("created_at", s.Offset(), err)
			}
			if seenCreatedAt {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"created_at"}}
			}
			seenCreatedAt = true
			result.CreatedAt, err = s.StringAVX2(true)
			if err != nil {
				return result, ggen.NewParseErr("created_at", s.Offset(), err)
			}
		case "author":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("author", s.Offset(), err)
			}
			if seenAuthor {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"author"}}
			}
			seenAuthor = true
			result.Author, err = s.StringAVX2(true)
			if err != nil {
				return result, ggen.NewParseErr("author", s.Offset(), err)
			}
		case "like_count":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("like_count", s.Offset(), err)
			}
			if seenLikeCount {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"like_count"}}
			}
			seenLikeCount = true
			result.LikeCount, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("like_count", s.Offset(), err)
			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{ownKey}}
		}

		err = s.SkipSpaceAVX2()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpaceAVX2()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenID {
				result.ID = 0
			}
			if !seenBody {
				result.Body = ""
			}
			if !seenCreatedAt {
				result.CreatedAt = ""
			}
			if !seenAuthor {
				result.Author = ""
			}
			if !seenLikeCount {
				result.LikeCount = 0
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s Post) JSONSize() int {
	size := 99
	size += len(s.Body) * 2
	size += len(s.CreatedAt) * 2
	size += len(s.Author) * 2
	return size
}

func (s Post) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"id\":"...)
	dst = strconv.AppendInt(dst, s.ID, 10)
	dst = append(dst, ",\"body\":\""...)
	dst = ggen.AppendStringNoHTMLAVX2(dst, s.Body)
	dst = append(dst, ",\"created_at\":\""...)
	dst = ggen.AppendStringNoHTMLAVX2(dst, s.CreatedAt)
	dst = append(dst, ",\"author\":\""...)
	dst = ggen.AppendStringNoHTMLAVX2(dst, s.Author)
	dst = append(dst, ",\"like_count\":"...)
	dst = strconv.AppendInt(dst, s.LikeCount, 10)
	return append(dst, '}'), nil
}

func (recv PostEnvelope) DecodeFrom(data []byte) (result PostEnvelope, i int, err error) {
	result = recv
	seenPost := false
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenPost {
			result.Post = Post{}
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		kew := ke + 5
		if kew > len(data) {
			kew = len(data)
		}
		for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.StringAVX2(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		switch key {
		case "post":
			if seenPost {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"post"}}
			}
			seenPost = true
			var consumed int
			result.Post, consumed, err = result.Post.DecodeFrom(data[i:])
			i += consumed
			if err != nil {
				return result, i, ggen.NewParseErrShift("post", i, consumed, err)
			}
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
				if i < len(data) && data[i] <= ' ' {
					i = ggen.SkipSpaceAVX2(data, i)
				}
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenPost {
				result.Post = Post{}
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv PostEnvelope) DecodeFromStream(s *ggen.Stream) (result PostEnvelope, err error) {
	result = recv
	seenPost := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpaceAVX2()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenPost {
			result.Post = Post{}
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "post":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("post", s.Offset(), err)
			}
			if seenPost {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"post"}}
			}
			seenPost = true
			result.Post, err = result.Post.DecodeFromStream(s)
			if err != nil {
				return result, ggen.NewParseErr("post", s.Offset(), err)
			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{ownKey}}
		}

		err = s.SkipSpaceAVX2()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpaceAVX2()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenPost {
				result.Post = Post{}
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s PostEnvelope) JSONSize() int {
	size := 9
	size += s.Post.JSONSize()
	return size
}

func (s PostEnvelope) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"post\":"...)
	if dst, err = s.Post.AppendJSON(dst); err != nil {
		return dst, err
	}
	return append(dst, '}'), nil
}

func (recv Feed) DecodeFrom(data []byte) (result Feed, i int, err error) {
	result = recv
	if result.Posts != nil {
		result.Posts = result.Posts[:0]
	}
	seenPosts := false
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		kew := ke + 6
		if kew > len(data) {
			kew = len(data)
		}
		for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.StringAVX2(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		switch key {
		case "posts":
			if seenPosts {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"posts"}}
			}
			seenPosts = true
			if i < len(data) && data[i] == 'n' {
				if i+4 > len(data) || data[i+1] != 'u' || data[i+2] != 'l' || data[i+3] != 'l' {
					return result, i, ggen.NewParseErr("posts", i, ggen.ErrBadLiteral)
				}
				i += 4
				result.Posts = nil
				break
			}
			if i >= len(data) || data[i] != '[' {
				return result, i, ggen.NewParseErr("posts", i, ggen.ErrBadArray)
			}
			i++
			if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
				if i < len(data) && data[i] <= ' ' {
					i = ggen.SkipSpaceAVX2(data, i)
				}
			}
			if i < len(data) && data[i] == ']' {
				if result.Posts == nil {
					result.Posts = []Post{}
				}
			} else {
				if result.Posts == nil {
					result.Posts = make([]Post, 0, ggenCap_Feed_Posts_Post)
				}
			}
			if i < len(data) && data[i] != ']' {
				for {
					if len(result.Posts) < cap(result.Posts) {
						result.Posts = result.Posts[:len(result.Posts)+1]
					} else {
						result.Posts = append(result.Posts, Post{})
					}
					var consumed int
					result.Posts[len(result.Posts)-1], consumed, err = result.Posts[len(result.Posts)-1].DecodeFrom(data[i:])
					i += consumed
					if err != nil {
						return result, i, ggen.NewParseErrShift("posts", i, consumed, err)
					}
					if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
						if i < len(data) && data[i] <= ' ' {
							i = ggen.SkipSpaceAVX2(data, i)
						}
					}
					if i < len(data) && data[i] == ',' {
						i++
						if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
							if i < len(data) && data[i] <= ' ' {
								i = ggen.SkipSpaceAVX2(data, i)
							}
						}
						if i >= len(data) || data[i] == ']' {
							return result, i, ggen.NewParseErr("posts", i, ggen.ErrBadArray)
						}
						continue
					}
					break
				}
			}
			if i >= len(data) || data[i] != ']' {
				return result, i, ggen.NewParseErr("posts", i, ggen.ErrBadArray)
			}
			i++
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
				if i < len(data) && data[i] <= ' ' {
					i = ggen.SkipSpaceAVX2(data, i)
				}
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv Feed) DecodeFromStream(s *ggen.Stream) (result Feed, err error) {
	result = recv
	if result.Posts != nil {
		result.Posts = result.Posts[:0]
	}
	seenPosts := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpaceAVX2()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "posts":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("posts", s.Offset(), err)
			}
			if seenPosts {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"posts"}}
			}
			seenPosts = true
			err = s.SkipSpaceAVX2()
			if err != nil {
				return result, ggen.NewParseErr("posts", s.Offset(), err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, ggen.NewParseErr("posts", s.Offset(), ggen.NotEOF(err, ggen.ErrBadArray))
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, ggen.NewParseErr("posts", s.Offset(), ggen.NotEOF(err, ggen.ErrBadLiteral))
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, ggen.NewParseErr("posts", s.Offset(), ggen.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Posts = nil
				break
			}
			err = s.ArrayOpen()
			if err != nil {
				return result, ggen.NewParseErr("posts", s.Offset(), err)
			}
			err = s.SkipSpaceAVX2()
			if err != nil {
				return result, ggen.NewParseErr("posts", s.Offset(), err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, ggen.NewParseErr("posts", s.Offset(), ggen.NotEOF(err, ggen.ErrBadArray))
				}
			}
			if s.Bytes()[s.Pos] == ']' {
				if result.Posts == nil {
					result.Posts = []Post{}
				}
			} else {
				if result.Posts == nil {
					result.Posts = make([]Post, 0, ggenCap_Feed_Posts_Post)
				}
			}
			for s.Bytes()[s.Pos] != ']' {
				if len(result.Posts) < cap(result.Posts) {
					result.Posts = result.Posts[:len(result.Posts)+1]
				} else {
					result.Posts = append(result.Posts, Post{})
				}
				result.Posts[len(result.Posts)-1], err = result.Posts[len(result.Posts)-1].DecodeFromStream(s)
				if err != nil {
					return result, ggen.NewParseErr("posts", s.Offset(), err)
				}
				err = s.SkipSpaceAVX2()
				if err != nil {
					return result, ggen.NewParseErr("posts", s.Offset(), err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, ggen.NewParseErr("posts", s.Offset(), ggen.NotEOF(err, ggen.ErrBadArray))
					}
				}
				if s.Bytes()[s.Pos] == ',' {
					s.Pos++
					err = s.SkipSpaceAVX2()
					if err != nil {
						return result, ggen.NewParseErr("posts", s.Offset(), err)
					}
					if s.Pos >= len(s.Bytes()) || s.Bytes()[s.Pos] == ']' {
						return result, ggen.NewParseErr("posts", s.Offset(), ggen.ErrBadArray)
					}
					continue
				}
				break
			}
			if s.Bytes()[s.Pos] != ']' {
				return result, ggen.NewParseErr("posts", s.Offset(), ggen.ErrBadArray)
			}
			s.Pos++
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{ownKey}}
		}

		err = s.SkipSpaceAVX2()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpaceAVX2()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s Feed) JSONSize() int {
	size := 14
	if n := len(s.Posts); n > 0 {
		size += n - 1
	}
	for i0 := range s.Posts {
		size += s.Posts[i0].JSONSize()
	}
	return size
}

func (s Feed) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"posts\":"...)
	if s.Posts == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Posts) > 0 {
			if dst, err = s.Posts[0].AppendJSON(dst); err != nil {
				return dst, err
			}
			for _, v0 := range s.Posts[1:] {
				dst = append(dst, ',')
				if dst, err = v0.AppendJSON(dst); err != nil {
					return dst, err
				}
			}
		}
		dst = append(dst, ']')
	}
	return append(dst, '}'), nil
}

func (recv CreatePost) DecodeFrom(data []byte) (result CreatePost, i int, err error) {
	result = recv
	seenBody := false
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenBody {
			result.Body = ""
		}
		if !seenBody {
			return result, i, &ggen.RequiredError{Pos: i, Path: []string{"body"}}
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		kew := ke + 5
		if kew > len(data) {
			kew = len(data)
		}
		for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.StringAVX2(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		switch key {
		case "body":
			if seenBody {
				i, err = ggen.SkipValueAVX2(data, i)
				if err != nil {
					return result, i, ggen.NewParseErr("body", i, err)
				}
			} else {
				seenBody = true
				if i >= len(data) || data[i] != '"' {
					return result, i, ggen.NewParseErr("body", i, ggen.ErrExpectString)
				}
				ke := i + 1
				if ke+32 <= len(data) {
					keV := archsimd.LoadUint8x32(data[ke:])
					keD := keV.Sub(archsimd.BroadcastUint8x32(0x20))
					keM := keV.Equal(archsimd.BroadcastUint8x32('"')).Or(keV.Equal(archsimd.BroadcastUint8x32('\\'))).Or(keD.Max(archsimd.BroadcastUint8x32(0x60)).Equal(keD)).ToBits()
					if keM != 0 {
						ke += bits.TrailingZeros32(keM)
					}
				} else {
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
						ke++
					}
				}
				if ke < len(data) && data[ke] == '"' {
					result.Body = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					result.Body, i, err = ggen.StringAVX2(data, i, true)
					if err != nil {
						return result, i, ggen.NewParseErr("body", i, err)
					}
				}
				result.Body = strings.TrimSpace(result.Body)
				if len(result.Body) == 0 {
					return result, i, &ggen.NotEmptyError{Pos: i, Path: []string{"body"}}
				}
				if len(result.Body) > 2000 {
					return result, i, &ggen.MaxRunesError{Pos: i, Path: []string{"body"}, Limit: 500, Got: utf8.RuneCountInString(result.Body)}
				} else if len(result.Body) > 500 {
					if rc := utf8.RuneCountInString(result.Body); rc > 500 {
						return result, i, &ggen.MaxRunesError{Pos: i, Path: []string{"body"}, Limit: 500, Got: rc}
					}
				}
			}
		default:
			i, err = ggen.SkipValueAVX2(data, i)
			if err != nil {
				return result, i, ggen.NewParseErr(key, i, err)
			}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
				if i < len(data) && data[i] <= ' ' {
					i = ggen.SkipSpaceAVX2(data, i)
				}
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenBody {
				result.Body = ""
			}
			if !seenBody {
				return result, i, &ggen.RequiredError{Pos: i, Path: []string{"body"}}
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv CreatePost) DecodeFromStream(s *ggen.Stream) (result CreatePost, err error) {
	result = recv
	seenBody := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpaceAVX2()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenBody {
			result.Body = ""
		}
		if !seenBody {
			return result, &ggen.RequiredError{Pos: s.Offset(), Path: []string{"body"}}
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "body":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("body", s.Offset(), err)
			}
			if seenBody {
				err = s.SkipValueAVX2()
				if err != nil {
					return result, ggen.NewParseErr("body", s.Offset(), err)
				}
			} else {
				seenBody = true
				result.Body, err = s.StringAVX2(true)
				if err != nil {
					return result, ggen.NewParseErr("body", s.Offset(), err)
				}
				result.Body = strings.TrimSpace(result.Body)
				if len(result.Body) == 0 {
					return result, &ggen.NotEmptyError{Pos: s.Offset(), Path: []string{"body"}}
				}
				if len(result.Body) > 2000 {
					return result, &ggen.MaxRunesError{Pos: s.Offset(), Path: []string{"body"}, Limit: 500, Got: utf8.RuneCountInString(result.Body)}
				} else if len(result.Body) > 500 {
					if rc := utf8.RuneCountInString(result.Body); rc > 500 {
						return result, &ggen.MaxRunesError{Pos: s.Offset(), Path: []string{"body"}, Limit: 500, Got: rc}
					}
				}

			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			err = s.SkipValueAVX2()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
		}

		err = s.SkipSpaceAVX2()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpaceAVX2()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenBody {
				result.Body = ""
			}
			if !seenBody {
				return result, &ggen.RequiredError{Pos: s.Offset(), Path: []string{"body"}}
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s CreatePost) JSONSize() int {
	size := 11
	size += len(s.Body) * 2
	return size
}

func (s CreatePost) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"body\":\""...)
	dst = ggen.AppendStringNoHTMLAVX2(dst, s.Body)
	return append(dst, '}'), nil
}

func (recv Like) DecodeFrom(data []byte) (result Like, i int, err error) {
	result = recv
	seenLiked := false
	seenAlreadyLiked := false
	seenPostID := false
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
		if i < len(data) && data[i] <= ' ' {
			i = ggen.SkipSpaceAVX2(data, i)
		}
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenLiked {
			result.Liked = false
		}
		if !seenAlreadyLiked {
			result.AlreadyLiked = false
		}
		if !seenPostID {
			result.PostID = 0
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		if ke+32 <= len(data) {
			keV := archsimd.LoadUint8x32(data[ke:])
			keD := keV.Sub(archsimd.BroadcastUint8x32(0x20))
			keM := keV.Equal(archsimd.BroadcastUint8x32('"')).Or(keV.Equal(archsimd.BroadcastUint8x32('\\'))).Or(keD.Max(archsimd.BroadcastUint8x32(0x60)).Equal(keD)).ToBits()
			if keM != 0 {
				ke += bits.TrailingZeros32(keM)
			}
		} else {
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.StringAVX2(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		switch key {
		case "liked":
			if seenLiked {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"liked"}}
			}
			seenLiked = true
			result.Liked, i, err = ggen.Bool(data, i)
			if err != nil {
				i = ggen.BoolEnd(data, i)
				return result, i, ggen.NewParseErr("liked", i, err)
			}
		case "already_liked":
			if seenAlreadyLiked {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"already_liked"}}
			}
			seenAlreadyLiked = true
			result.AlreadyLiked, i, err = ggen.Bool(data, i)
			if err != nil {
				i = ggen.BoolEnd(data, i)
				return result, i, ggen.NewParseErr("already_liked", i, err)
			}
		case "post_id":
			if seenPostID {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"post_id"}}
			}
			seenPostID = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("post_id", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("post_id", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("post_id", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("post_id", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			result.PostID = n
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = ggen.SkipSpaceAVX2(data, i)
			}
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			if i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
				if i < len(data) && data[i] <= ' ' {
					i = ggen.SkipSpaceAVX2(data, i)
				}
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenLiked {
				result.Liked = false
			}
			if !seenAlreadyLiked {
				result.AlreadyLiked = false
			}
			if !seenPostID {
				result.PostID = 0
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv Like) DecodeFromStream(s *ggen.Stream) (result Like, err error) {
	result = recv
	seenLiked := false
	seenAlreadyLiked := false
	seenPostID := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpaceAVX2()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenLiked {
			result.Liked = false
		}
		if !seenAlreadyLiked {
			result.AlreadyLiked = false
		}
		if !seenPostID {
			result.PostID = 0
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyViewAVX2(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "liked":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("liked", s.Offset(), err)
			}
			if seenLiked {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"liked"}}
			}
			seenLiked = true
			result.Liked, err = s.Bool()
			if err != nil {
				return result, ggen.NewParseErr("liked", s.Offset(), err)
			}
		case "already_liked":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("already_liked", s.Offset(), err)
			}
			if seenAlreadyLiked {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"already_liked"}}
			}
			seenAlreadyLiked = true
			result.AlreadyLiked, err = s.Bool()
			if err != nil {
				return result, ggen.NewParseErr("already_liked", s.Offset(), err)
			}
		case "post_id":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("post_id", s.Offset(), err)
			}
			if seenPostID {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"post_id"}}
			}
			seenPostID = true
			result.PostID, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("post_id", s.Offset(), err)
			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{ownKey}}
		}

		err = s.SkipSpaceAVX2()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpaceAVX2()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenLiked {
				result.Liked = false
			}
			if !seenAlreadyLiked {
				result.AlreadyLiked = false
			}
			if !seenPostID {
				result.PostID = 0
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s Like) JSONSize() int {
	size := 68
	return size
}

func (s Like) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"liked\":"...)
	dst = strconv.AppendBool(dst, s.Liked)
	dst = append(dst, ",\"already_liked\":"...)
	dst = strconv.AppendBool(dst, s.AlreadyLiked)
	dst = append(dst, ",\"post_id\":"...)
	dst = strconv.AppendInt(dst, s.PostID, 10)
	return append(dst, '}'), nil
}
